### ISSUE TITLE
Add gradle task to initialize  idl submodule

### ISSUE THREAD

**Issue by nklmish** [uber/jaeger-client-java#15]
When I execute:

``` bash
./gradlew clean test
```

I receive

``` java
Jar was not signed since this was a snapshot release.
Jar was not signed since this was a snapshot release.
Jar was not signed since this was a snapshot release.
:jaeger-context:clean
:jaeger-core:clean
:jaeger-jaxrs2:clean UP-TO-DATE
:jaeger-context:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:jaeger-context:licenseFormatMain UP-TO-DATE
:jaeger-context:licenseFormatTest UP-TO-DATE
:jaeger-context:licenseFormat UP-TO-DATE
:jaeger-context:processResources UP-TO-DATE
:jaeger-context:classes
:jaeger-context:compileTestJava UP-TO-DATE
:jaeger-context:processTestResources UP-TO-DATE
:jaeger-context:testClasses UP-TO-DATE
:jaeger-context:test UP-TO-DATE
:jaeger-core:compileThrift UP-TO-DATE
:jaeger-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/Span.java:29: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Endpoint;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/Span.java:39: error: cannot find symbol
    private Endpoint peer;
            ^
  symbol:   class Endpoint
  location: class Span
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/Span.java:65: error: cannot find symbol
    public Endpoint getPeer() {
           ^
  symbol:   class Endpoint
  location: class Span
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:24: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Annotation;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:25: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.AnnotationType;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:26: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.BinaryAnnotation;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:27: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Endpoint;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:28: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.zipkincoreConstants;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:43: error: package com.twitter.zipkin.thriftjava does not exist
    public static com.twitter.zipkin.thriftjava.Span convertSpan(Span span) {
                                               ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:63: error: cannot find symbol
    private static List<Annotation> buildAnnotations(Span span, Endpoint host) {
                                                                ^
  symbol:   class Endpoint
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:63: error: cannot find symbol
    private static List<Annotation> buildAnnotations(Span span, Endpoint host) {
                        ^
  symbol:   class Annotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:89: error: cannot find symbol
    private static List<BinaryAnnotation> buildBinaryAnnotations(Span span, Endpoint host) {
                                                                            ^
  symbol:   class Endpoint
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:89: error: cannot find symbol
    private static List<BinaryAnnotation> buildBinaryAnnotations(Span span, Endpoint host) {
                        ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:129: error: cannot find symbol
    private static BinaryAnnotation buildBinaryAnnotation(String tagKey, Object tagValue) {
                   ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/Sender.java:24: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Span;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/Sender.java:28: error: cannot find symbol
    int append(Span span) throws SenderException;
               ^
  symbol:   class Span
  location: interface Sender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/RemoteReporter.java:113: error: package com.twitter.zipkin.thriftjava does not exist
        private final com.twitter.zipkin.thriftjava.Span span;
                                                   ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/RemoteReporter.java:115: error: package com.twitter.zipkin.thriftjava does not exist
        public AppendCommand(com.twitter.zipkin.thriftjava.Span span) {
                                                          ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:26: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.ProbabilisticSamplingStrategy;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:27: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.RateLimitingSamplingStrategy;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:28: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.SamplingStrategyResponse;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:29: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.SamplingStrategyType;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/SamplingManager.java:25: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.SamplingStrategyResponse;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:67: error: cannot find symbol
    private SamplingStrategyResponse jsonStringToSamplingStrategy(String jsonString) {
            ^
  symbol:   class SamplingStrategyResponse
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:104: error: cannot find symbol
    public SamplingStrategyResponse getSamplingStrategy(String serviceName) throws SamplingStrategyErrorException {
           ^
  symbol:   class SamplingStrategyResponse
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/SamplingManager.java:28: error: cannot find symbol
    SamplingStrategyResponse getSamplingStrategy(String serviceName) throws SamplingStrategyErrorException;
    ^
  symbol:   class SamplingStrategyResponse
  location: interface SamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:27: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.ProbabilisticSamplingStrategy;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:28: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.RateLimitingSamplingStrategy;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:29: error: package com.uber.jaeger.thrift.sampling_manager does not exist
import com.uber.jaeger.thrift.sampling_manager.SamplingStrategyResponse;
                                              ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:97: error: cannot find symbol
    private Sampler extractSampler(SamplingStrategyResponse response) throws UnknownSamplingStrategyException {
                                   ^
  symbol:   class SamplingStrategyResponse
  location: class RemoteControlledSampler
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:24: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Span;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:31: error: cannot find symbol
    private List<Span> appended;
                 ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:32: error: cannot find symbol
    private List<Span> flushed;
                 ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:33: error: cannot find symbol
    private List<Span> received;
                 ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:41: error: cannot find symbol
    public List<Span> getAppended() {
                ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:45: error: cannot find symbol
    public List<Span> getFlushed() {
                ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:49: error: cannot find symbol
    public List<Span> getReceived() {
                ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/InMemorySender.java:54: error: cannot find symbol
    public int append(Span span) throws SenderException {
                      ^
  symbol:   class Span
  location: class InMemorySender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:27: error: package com.twitter.zipkin.thriftjava does not exist
import com.twitter.zipkin.thriftjava.Span;
                                    ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:28: error: package com.uber.jaeger.agent.thrift does not exist
import com.uber.jaeger.agent.thrift.Agent;
                                   ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:42: error: package Agent does not exist
    private Agent.Client udpClient;
                 ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:43: error: cannot find symbol
    private List<Span> spanBuffer;
                 ^
  symbol:   class Span
  location: class UDPSender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:70: error: cannot find symbol
    int getSizeOfSerializedSpan(Span span) throws SenderException {
                                ^
  symbol:   class Span
  location: class UDPSender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:86: error: cannot find symbol
    public int append(Span span) throws SenderException {
                      ^
  symbol:   class Span
  location: class UDPSender
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/Span.java:68: error: cannot find symbol
                peer = new Endpoint();
                           ^
  symbol:   class Endpoint
  location: class Span
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:45: error: cannot find symbol
        Endpoint host = new Endpoint(
        ^
  symbol:   class Endpoint
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:45: error: cannot find symbol
        Endpoint host = new Endpoint(
                            ^
  symbol:   class Endpoint
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:51: error: package com.twitter.zipkin.thriftjava does not exist
        return new com.twitter.zipkin.thriftjava.Span(
                                                ^
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:64: error: cannot find symbol
        List<Annotation> annotations = new ArrayList<>();
             ^
  symbol:   class Annotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:67: error: cannot find symbol
            String startLabel = zipkincoreConstants.SERVER_RECV;
                                ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:68: error: cannot find symbol
            String endLabel = zipkincoreConstants.SERVER_SEND;
                              ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:70: error: cannot find symbol
                startLabel = zipkincoreConstants.CLIENT_SEND;
                             ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:71: error: cannot find symbol
                endLabel = zipkincoreConstants.CLIENT_RECV;
                           ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:74: error: cannot find symbol
            annotations.add(new Annotation(span.getStart(), startLabel).setHost(host));
                                ^
  symbol:   class Annotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:75: error: cannot find symbol
            annotations.add(new Annotation(span.getStart() + span.getDuration(), endLabel).setHost(host));
                                ^
  symbol:   class Annotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:81: error: cannot find symbol
                annotations.add(new Annotation(logData.getTime(), logData.getMessage()));
                                    ^
  symbol:   class Annotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:90: error: cannot find symbol
        List<BinaryAnnotation> binaryAnnotations = new ArrayList<BinaryAnnotation>();
             ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:90: error: cannot find symbol
        List<BinaryAnnotation> binaryAnnotations = new ArrayList<BinaryAnnotation>();
                                                                 ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:93: error: cannot find symbol
            String label = span.isRPCClient() ? zipkincoreConstants.SERVER_ADDR : zipkincoreConstants.CLIENT_ADDR;
                                                ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:93: error: cannot find symbol
            String label = span.isRPCClient() ? zipkincoreConstants.SERVER_ADDR : zipkincoreConstants.CLIENT_ADDR;
                                                                                  ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:98: error: cannot find symbol
                .setAnnotation_type(AnnotationType.BOOL)
                                    ^
  symbol:   variable AnnotationType
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:95: error: cannot find symbol
            binaryAnnotations.add(new BinaryAnnotation()
                                      ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:113: error: cannot find symbol
                .setAnnotation_type(AnnotationType.STRING)
                                    ^
  symbol:   variable AnnotationType
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:111: error: cannot find symbol
            binaryAnnotations.add(new BinaryAnnotation().setKey(zipkincoreConstants.LOCAL_COMPONENT)
                                                                ^
  symbol:   variable zipkincoreConstants
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:111: error: cannot find symbol
            binaryAnnotations.add(new BinaryAnnotation().setKey(zipkincoreConstants.LOCAL_COMPONENT)
                                      ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:130: error: cannot find symbol
        BinaryAnnotation banno = new BinaryAnnotation()
        ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:130: error: cannot find symbol
        BinaryAnnotation banno = new BinaryAnnotation()
                                     ^
  symbol:   class BinaryAnnotation
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/reporters/protocols/ThriftSpanConverter.java:138: error: cannot find symbol
        banno.setValue(stringTagValue.getBytes()).setAnnotation_type(AnnotationType.STRING);
                                                                     ^
  symbol:   variable AnnotationType
  location: class ThriftSpanConverter
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:75: error: cannot find symbol
        SamplingStrategyType samplingType = SamplingStrategyType.findByValue((Integer) result.get("strategyType"));
        ^
  symbol:   class SamplingStrategyType
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:75: error: cannot find symbol
        SamplingStrategyType samplingType = SamplingStrategyType.findByValue((Integer) result.get("strategyType"));
                                            ^
  symbol:   variable SamplingStrategyType
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:76: error: cannot find symbol
        if (samplingType == SamplingStrategyType.PROBABILISTIC) {
                            ^
  symbol:   variable SamplingStrategyType
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:85: error: cannot find symbol
                    .setProbabilisticSampling(new ProbabilisticSamplingStrategy(samplingRate));
                                                  ^
  symbol:   class ProbabilisticSamplingStrategy
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:84: error: cannot find symbol
            return new SamplingStrategyResponse(samplingType)
                       ^
  symbol:   class SamplingStrategyResponse
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:88: error: cannot find symbol
        if (samplingType == SamplingStrategyType.RATE_LIMITING) {
                            ^
  symbol:   variable SamplingStrategyType
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:97: error: cannot find symbol
                    .setRateLimitingSampling(new RateLimitingSamplingStrategy((short)maxTracesPerSecond));
                                                 ^
  symbol:   class RateLimitingSamplingStrategy
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java:96: error: cannot find symbol
            return new SamplingStrategyResponse(samplingType)
                       ^
  symbol:   class SamplingStrategyResponse
  location: class HTTPSamplingManager
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:70: error: cannot find symbol
        SamplingStrategyResponse response;
        ^
  symbol:   class SamplingStrategyResponse
  location: class RemoteControlledSampler
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:99: error: cannot find symbol
            ProbabilisticSamplingStrategy strategy = response.getProbabilisticSampling();
            ^
  symbol:   class ProbabilisticSamplingStrategy
  location: class RemoteControlledSampler
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/RemoteControlledSampler.java:104: error: cannot find symbol
            RateLimitingSamplingStrategy strategy = response.getRateLimitingSampling();
            ^
  symbol:   class RateLimitingSamplingStrategy
  location: class RemoteControlledSampler
/Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/senders/UDPSender.java:64: error: package Agent does not exist
        udpClient = new Agent.Client(new TCompactProtocol(udpTransport));
                             ^
Note: /Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/nklmish/workspace/jaeger-client-java/jaeger-core/src/main/java/com/uber/jaeger/samplers/HTTPSamplingManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
80 errors
1 warning
:jaeger-core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jaeger-core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by yurishkuro** [comment]
@nklmish make sure you have initialized the submodule. I've just updated the README

**Comment by oibe** [comment]
So I did two things.

**Comment by yurishkuro** [comment]
@oibe can we add a custom step in the build to check for the presence of thrift files in the `idl` directory and fail the build with a clear warning that the submodule needs to be initialized?

Also, why is it when submodule is not initialized the build does not fail on generating sources, and instead fails in the compile phase?

**Comment by nklmish** [comment]
@yurishkuro @oibe  initialising and updating the submodule helped, but if thrift is not installed locally then the build will still fail. However, after installing thrift (version 0.9.3) , I am still getting the following error message:

```java
[ERROR:/Users/nklmish/workspace/jaeger-client-java/idl/.travis.yml:1] (last token was 'sudo')

syntax error
[FAILURE:/Users/nklmish/workspace/jaeger-client-java/idl/.travis.yml:1] Parser error during include pass.:jaeger-core:compileThrift FAILED

FAILURE: Build failed with an exception.
```

**Comment by nklmish** [comment]
@yurishkuro May be rather then marking the build as failed in case of missing thrift files, we can create a custom gradle task which can:
1. Check If idl directory is initialised properly 
2. In case if the idl is not initialised , then log console message "initialising idl..." and execute the necessary command to initialise and update the idl module. 
?

**Comment by yurishkuro** [comment]
Sure, if invoking git is doable from Gradle

**Comment by alshopov** [comment]
Perhaps close this - the least magical way to invoke git from gradle is closed so this will probably not be done.
